/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KZcM1he8mac
 */
import Link from "next/link"

export function LiveSites() {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4 p-4 md:p-6">
      <div className="relative group overflow-hidden rounded-lg">
        <Link className="absolute inset-0 z-10" href="#">
          <span className="sr-only">View Project 1</span>
        </Link>
        <img
          alt="Project 1"
          className="object-cover w-full h-30"
          height={150}
          src="/placeholder.svg"
          style={{
            aspectRatio: "200/150",
            objectFit: "cover",
          }}
          width={200}
        />
        <div className="bg-white p-2 dark:bg-gray-950">
          <h3 className="font-semibold text-sm md:text-md">Project 1</h3>
          <p className="text-xs text-gray-500 dark:text-gray-400">HTML, CSS, JavaScript</p>
          <Link className="text-blue-500 hover:underline" href="#">
            Visit Site
          </Link>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <Link className="absolute inset-0 z-10" href="#">
          <span className="sr-only">View Project 2</span>
        </Link>
        <img
          alt="Project 2"
          className="object-cover w-full h-30"
          height={150}
          src="/placeholder.svg"
          style={{
            aspectRatio: "200/150",
            objectFit: "cover",
          }}
          width={200}
        />
        <div className="bg-white p-2 dark:bg-gray-950">
          <h3 className="font-semibold text-sm md:text-md">Project 2</h3>
          <p className="text-xs text-gray-500 dark:text-gray-400">React, Node.js, Express</p>
          <Link className="text-blue-500 hover:underline" href="#">
            Visit Site
          </Link>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <Link className="absolute inset-0 z-10" href="#">
          <span className="sr-only">View Project 3</span>
        </Link>
        <img
          alt="Project 3"
          className="object-cover w-full h-30"
          height={150}
          src="/placeholder.svg"
          style={{
            aspectRatio: "200/150",
            objectFit: "cover",
          }}
          width={200}
        />
        <div className="bg-white p-2 dark:bg-gray-950">
          <h3 className="font-semibold text-sm md:text-md">Project 3</h3>
          <p className="text-xs text-gray-500 dark:text-gray-400">Python, Django, PostgreSQL</p>
          <Link className="text-blue-500 hover:underline" href="#">
            Visit Site
          </Link>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <Link className="absolute inset-0 z-10" href="#">
          <span className="sr-only">View Project 4</span>
        </Link>
        <img
          alt="Project 4"
          className="object-cover w-full h-30"
          height={150}
          src="/placeholder.svg"
          style={{
            aspectRatio: "200/150",
            objectFit: "cover",
          }}
          width={200}
        />
        <div className="bg-white p-2 dark:bg-gray-950">
          <h3 className="font-semibold text-sm md:text-md">Project 4</h3>
          <p className="text-xs text-gray-500 dark:text-gray-400">Vue.js, Firebase, Cloud Functions</p>
          <Link className="text-blue-500 hover:underline" href="#">
            Visit Site
          </Link>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <Link className="absolute inset-0 z-10" href="#">
          <span className="sr-only">View Project 5</span>
        </Link>
        <img
          alt="Project 5"
          className="object-cover w-full h-30"
          height={150}
          src="/placeholder.svg"
          style={{
            aspectRatio: "200/150",
            objectFit: "cover",
          }}
          width={200}
        />
        <div className="bg-white p-2 dark:bg-gray-950">
          <h3 className="font-semibold text-sm md:text-md">Project 5</h3>
          <p className="text-xs text-gray-500 dark:text-gray-400">Angular, TypeScript, RxJS</p>
          <Link className="text-blue-500 hover:underline" href="#">
            Visit Site
          </Link>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <Link className="absolute inset-0 z-10" href="#">
          <span className="sr-only">View Project 6</span>
        </Link>
        <img
          alt="Project 6"
          className="object-cover w-full h-30"
          height={150}
          src="/placeholder.svg"
          style={{
            aspectRatio: "200/150",
            objectFit: "cover",
          }}
          width={200}
        />
        <div className="bg-white p-2 dark:bg-gray-950">
          <h3 className="font-semibold text-sm md:text-md">Project 6</h3>
          <p className="text-xs text-gray-500 dark:text-gray-400">Svelte, Rollup, Sapper</p>
          <Link className="text-blue-500 hover:underline" href="#">
            Visit Site
          </Link>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <Link className="absolute inset-0 z-10" href="#">
          <span className="sr-only">View Project 7</span>
        </Link>
        <img
          alt="Project 7"
          className="object-cover w-full h-30"
          height={150}
          src="/placeholder.svg"
          style={{
            aspectRatio: "200/150",
            objectFit: "cover",
          }}
          width={200}
        />
        <div className="bg-white p-2 dark:bg-gray-950">
          <h3 className="font-semibold text-sm md:text-md">Project 7</h3>
          <p className="text-xs text-gray-500 dark:text-gray-400">Rust, WebAssembly, Yew</p>
          <Link className="text-blue-500 hover:underline" href="#">
            Visit Site
          </Link>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <Link className="absolute inset-0 z-10" href="#">
          <span className="sr-only">View Project 8</span>
        </Link>
        <img
          alt="Project 8"
          className="object-cover w-full h-30"
          height={150}
          src="/placeholder.svg"
          style={{
            aspectRatio: "200/150",
            objectFit: "cover",
          }}
          width={200}
        />
        <div className="bg-white p-2 dark:bg-gray-950">
          <h3 className="font-semibold text-sm md:text-md">Project 8</h3>
          <p className="text-xs text-gray-500 dark:text-gray-400">Elm, Elixir, Phoenix</p>
          <Link className="text-blue-500 hover:underline" href="#">
            Visit Site
          </Link>
        </div>
      </div>
    </div>
  )
}
